// Permanent upgrades — purchased with quills, persist across publish rounds.
// permUpgradeLevels[id] tracks the current level (default 0).
//
// Two shapes:
//   levels-array: { id, name, maxLevel, levels: [{ cost, unlocksQty?, boxLabel?, label }] }
//   formula:      { id, name, maxLevel, costFormula, boxLabel, nextLabel, maxedLabel }

export const PERM_UPGRADES = [
  {
    id:       "bulk_buying",
    name:     "Bulk Buying",
    maxLevel: 4,
    levels: [
      { cost: 1,  unlocksQty: 5,     label: "Unlocks ×5 buy"   },
      { cost: 5,  unlocksQty: 10,    label: "Unlocks ×10 buy"  },
      { cost: 10, unlocksQty: 100,   label: "Unlocks ×100 buy" },
      { cost: 25, unlocksQty: "max", label: "Unlocks Max buy"  },
    ],
  },
  {
    id:          "max_letters",
    name:        "Letter Storage",
    maxLevel:    95,   // 50 + 95×10 = 1,000
    costFormula: (level) => 5 + level * 5,
    boxLabel:    (level) => `${50 + level * 10}`,
    nextLabel:   (level) => `→ ${50 + (level + 1) * 10} max letters`,
    maxedLabel:  "Max storage reached (1,000)",
  },
  {
    id:          "ink_multiplier",
    name:        "Ink Multiplier",
    maxLevel:    1000,
    costFormula: (level) => 10 + level * 10,
    boxLabel:    (level) => `×${Math.pow(1.01, level).toFixed(2)}`,
    nextLabel:   (level) => `→ ×${Math.pow(1.01, level + 1).toFixed(4)} ink`,
    maxedLabel:  "Max ink multiplier reached",
  },
  {
    id:       "monkey_typewriter",
    name:     "Monkey with a Typewriter",
    maxLevel: 20,
    levels: [
      { cost:         100, boxLabel:  "1", label: "A monkey taps away at a typewriter..." },
      { cost:         300, boxLabel:  "2", label: "A second monkey joins the effort" },
      { cost:         700, boxLabel:  "3", label: "Three monkeys, three typewriters" },
      { cost:       1_500, boxLabel:  "4", label: "Four monkeys filling pages" },
      { cost:       3_000, boxLabel:  "5", label: "Five monkeys — they're getting somewhere" },
      { cost:       6_000, boxLabel:  "6", label: "Six monkeys, the room is getting noisy" },
      { cost:      12_000, boxLabel:  "7", label: "Seven monkeys and a growing stack of pages" },
      { cost:      25_000, boxLabel:  "8", label: "Eight monkeys working through the night" },
      { cost:      50_000, boxLabel:  "9", label: "Nine monkeys — Shakespeare is getting worried" },
      { cost:     100_000, boxLabel: "10", label: "Ten monkeys, two full columns of typewriters" },
      { cost:     200_000, boxLabel: "11", label: "Eleven monkeys — productivity is surging" },
      { cost:     400_000, boxLabel: "12", label: "Twelve monkeys and a mountain of rough drafts" },
      { cost:     800_000, boxLabel: "13", label: "Thirteen monkeys — statistically, it's working" },
      { cost:   1_500_000, boxLabel: "14", label: "Fourteen monkeys and the complete works of Austen" },
      { cost:   3_000_000, boxLabel: "15", label: "Fifteen monkeys — the infinite library grows" },
      { cost:   6_000_000, boxLabel: "16", label: "Sixteen monkeys — four full columns, somehow" },
      { cost:  12_000_000, boxLabel: "17", label: "Seventeen monkeys and a deafening clatter" },
      { cost:  25_000_000, boxLabel: "18", label: "Eighteen monkeys — they've begun peer-reviewing" },
      { cost:  50_000_000, boxLabel: "19", label: "Nineteen monkeys and a sprawling bibliography" },
      { cost: 100_000_000, boxLabel: "20", label: "Twenty monkeys — the complete works, eventually" },
    ],
  },
  {
    id:          "monkey_intuition",
    name:        "Monkey Intuition",
    maxLevel:    90,
    lockedIf:    ({ permUpgradeLevels }) => (permUpgradeLevels["monkey_typewriter"] || 0) < 1,
    lockedLabel: "Requires: 1 Monkey with a Typewriter",
    costFormula: (L) => Math.round(50_000 * Math.pow(1.12, L)),
    boxLabel:    (L) => `${10 + L}%`,
    nextLabel:   (L) => `→ ${10 + L + 1}% find chance`,
    maxedLabel:  "Perfect monkey intuition (100%)",
  },
  {
    id:          "monkey_efficiency",
    name:        "Monkey Efficiency",
    maxLevel:    27,
    lockedIf:    ({ permUpgradeLevels }) => (permUpgradeLevels["monkey_typewriter"] || 0) < 1,
    lockedLabel: "Requires: 1 Monkey with a Typewriter",
    costFormula: (L) => Math.round(150_000 * Math.pow(1.18, L)),
    boxLabel:    (L) => `${300 - L * 10}s`,
    nextLabel:   (L) => `→ ${300 - (L + 1) * 10}s search time`,
    maxedLabel:  "Maximum monkey efficiency (30s)",
  },
  {
    id:          "monkey_tile_chance",
    name:        "Monkey Precision",
    maxLevel:    1000,
    lockedIf:    ({ permUpgradeLevels }) => (permUpgradeLevels["monkey_typewriter"] || 0) < 1,
    lockedLabel: "Requires: 1 Monkey with a Typewriter",
    costFormula: (L) => Math.round(2_000 * Math.pow(1.012, L)),
    boxLabel:    (L) => `${(L * 0.1).toFixed(1)}%`,
    nextLabel:   (L) => `→ ${((L + 1) * 0.1).toFixed(1)}% per-letter bonus chance`,
    maxedLabel:  "Max bonus tile chance (100%)",
  },
  {
    id:          "monkey_tile_limit",
    name:        "Monkey Artistry",
    maxLevel:    9,
    lockedIf:    ({ permUpgradeLevels }) => (permUpgradeLevels["monkey_typewriter"] || 0) < 1,
    lockedLabel: "Requires: 1 Monkey with a Typewriter",
    costFormula: (L) => Math.round(1_000_000 * Math.pow(2.5, L)),
    boxLabel:    (L) => `${L + 1}`,
    nextLabel:   (L) => `→ up to ${L + 2} bonus tiles per word`,
    maxedLabel:  "Max bonus tiles per word (10)",
  },
];
